- job:
    name: oslo.messaging-tox-py36-func-scenario01
    parent: openstack-tox-py36
    vars:
      tox_envlist: py36-func-scenario01
      bindep_profile: rabbit

- job:
    name: oslo.messaging-tox-py36-func-scenario02
    parent: openstack-tox-py36
    vars:
      tox_envlist: py36-func-scenario02
      bindep_profile: rabbit kafka

- job:
    name: oslo.messaging-tox-py36-func-scenario03
    parent: openstack-tox-py36
    vars:
      tox_envlist: py36-func-scenario03
      bindep_profile: rabbit

- job:
    name: oslo.messaging-tox-py36-func-scenario04
    parent: openstack-tox-py36
    vars:
      tox_envlist: py36-func-scenario04
      bindep_profile: kafka

# Begin v3 native jobs
# See https://docs.openstack.org/devstack/latest/


- job:
    name: oslo.messaging-devstack-tempest-full-base
    description: |
      Base for all devstack based tempest full testing jobs (with
      neutron)
    abstract: true
    parent: devstack-tempest
    timeout: 10800
    required-projects:
      - openstack/oslo.messaging
    vars:
      tox_envlist: full


- job:
    name: oslo.messaging-src-dsvm-full-rabbit
    description: |
      Run full tempest tests against rabbitmq
    parent: oslo.messaging-devstack-tempest-full-base


- job:
    name: oslo.messaging-src-dsvm-full-amqp1-hybrid
    description: |
      Run the full tempest tests using the AMQP 1.0 driver for RPC and
      RabbitMQ for Notifications.
    parent: oslo.messaging-devstack-tempest-full-base
    required-projects:
      - openstack/devstack-plugin-amqp1
    vars:
      devstack_localrc:
        AMQP1_SERVICE: qpid-hybrid
      devstack_plugins:
        devstack-plugin-amqp1: https://opendev.org/openstack/devstack-plugin-amqp1
      zuul_copy_output:
        '{{ devstack_log_dir }}/qdrouterd.log': logs


- job:
    name: oslo.messaging-src-dsvm-full-kafka-hybrid
    description: |
      Run the full tempest tests using the AMQP 1.0 driver for RPC and
      Apache Kafka for Notifications.
    parent: oslo.messaging-devstack-tempest-full-base
    required-projects:
      - openstack/devstack-plugin-kafka
    vars:
      devstack_plugins:
        devstack-plugin-kafka: https://opendev.org/openstack/devstack-plugin-kafka
      zuul_copy_output:
        '{{ devstack_log_dir }}/server.log': logs


# End v3 native jobs


- job:
    name: oslo.messaging-src-grenade-dsvm
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-src-grenade-dsvm/run.yaml
    post-run: playbooks/oslo.messaging-src-grenade-dsvm/post.yaml
    timeout: 10800
    required-projects:
      - openstack/grenade
      - openstack/devstack-gate
      - openstack/oslo.messaging
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$

- job:
    name: oslo.messaging-src-grenade-dsvm-multinode
    parent: legacy-dsvm-base-multinode
    run: playbooks/oslo.messaging-src-grenade-dsvm-multinode/run.yaml
    post-run: playbooks/oslo.messaging-src-grenade-dsvm-multinode/post.yaml
    timeout: 10800
    required-projects:
      - openstack/grenade
      - openstack/devstack-gate
      - openstack/oslo.messaging
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
    nodeset: legacy-ubuntu-xenial-2-node


- project:
    templates:
      - check-requirements
      - lib-forward-testing-python3
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-ussuri-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - oslo.messaging-tox-py36-func-scenario01
        - oslo.messaging-tox-py36-func-scenario02:
            voting: false
        - oslo.messaging-tox-py36-func-scenario03:
            voting: false
        - oslo.messaging-tox-py36-func-scenario04:
            voting: false
        - oslo.messaging-src-dsvm-full-rabbit
        - oslo.messaging-src-dsvm-full-amqp1-hybrid:
            voting: false
        - oslo.messaging-src-dsvm-full-kafka-hybrid:
            voting: false
        - oslo.messaging-src-grenade-dsvm:
            voting: false
        - oslo.messaging-src-grenade-dsvm-multinode:
            voting: false

    gate:
      jobs:
        - oslo.messaging-tox-py36-func-scenario01
        - oslo.messaging-src-dsvm-full-rabbit
